### ISSUE TITLE
sms.db malformed

### ISSUE THREAD

**Issue by sebay** [MaxiHuHe04/iTunes-Backup-Explorer#1]
Hi,
I have exported sms.db but am unable to use it with sqlite3:
Error: database disk image is malformed
Any idea what could be the issue and how I could troubleshoot?
Thank you.

**Comment by sebay** [comment]
It seems my database is really corrupted. May not have to do with itunes backup.

**Comment by danem** [comment]
@sebay 

Any resolution on this? I've run into the same issue.
