### ISSUE TITLE
Can't open backup

### ISSUE THREAD

**Issue by Zoxplers** [MaxiHuHe04/iTunes-Backup-Explorer#11]
I get an error that says me.maxih.itunes_backup_explorer.api.BackupReadException: java.util.NoSuchElementException: No value present

**Comment by MaxiHuHe04** [comment]
This should hopefully be fixed now, see #8. If there are still problems, please reopen the issue and paste the log of launching the program using `java -jar itunes-backup-explorer-1.3.jar` in a terminal.
