### ISSUE TITLE
Can't open the backup file

### ISSUE THREAD

**Issue by ebugday81** [MaxiHuHe04/iTunes-Backup-Explorer#14]
I'm trying to open the file on Mac OS 11.7 where my backups are stored at `~/Library/Application Support/MobileSync`

I changed the path under preferences, but I still can't open the backup. When double clicking on the specific backup folder it opens the folder and lists the files in it. The only files I can open from now are manifest.plist and Status.plist. See below.
I expect to double click on the folder and load it in the application, not?

Backups are older maybe this might be a problem?

![image](https://user-images.githubusercontent.com/73993405/224457658-2ae8cf99-fc55-4de0-a31f-1d3f4a8b6bed.png)

![image](https://user-images.githubusercontent.com/73993405/224457672-b170510d-b8c1-430a-a8b6-13c72d21353e.png)

**Comment by MaxiHuHe04** [comment]
Hi,
Normally, you would be able to double click on the Manifest.plist there to open it.
However, this backup looks rather old. My program currently only supports backups of iOS versions starting with 10.2 made with more or less recent versions of iTunes.
