### ISSUE TITLE
Question regarding the privacy policy

### ISSUE THREAD

**Issue by aviv926** [MaxiHuHe04/iTunes-Backup-Explorer#15]
First of all I want to say that this is great software and it works exceptionally well and I totally appreciate your investment here!

I wanted to ask about the privacy policy of this tool, I know that of course if it appears on GitHub
 it is open source and anyone can see edit and suggest changes to the code
 but anyway I don't usually read the code in its entirety and I usually access the privacy policy provided by the developer
 I haven't seen mention of this in the Read_me.md file so I wanted to ask if this software/code collects any data?

Thanks!

**Comment by MaxiHuHe04** [comment]
Hi @aviv926,
I'm very glad you found it useful.

Thank you for asking. Admittedly, I haven't even thought about a privacy policy yet. I don't collect any data and don't plan to change that in the near future. At the moment, the program actually does not connect to the internet at all.
If that should change at some point, I will make a notice.

**Comment by aviv926** [comment]
> Hi @aviv926, I'm very glad you found it useful.
> 
> Thank you for asking. Admittedly, I haven't even thought about a privacy policy yet. I don't collect any data and don't plan to change that in the near future. At the moment, the program actually does not connect to the internet at all. If that should change at some point, I will make a notice.

Thank you for this information

Maybe you should add this information to readme.md
