### ISSUE TITLE
How to open encrypted backup?

### ISSUE THREAD

**Issue by dnrm** [MaxiHuHe04/iTunes-Backup-Explorer#19]
Hi! I managed to get the program running but I don't know how to input the password for the encrypted backup. Am I supposed to pass any parameter when executing the file or something? 

Thank you for your help :)

**Comment by dnrm** [comment]
I just realised this error pops up in the terminal window:

```
Exception in thread "JavaFX Application Thread" java.lang.NoSuchFieldError: DIALOG
```

**Comment by dnrm** [comment]
Solved, just updated the `pom.xml` dependencies from javafx to version 20.

Pastebin: https://pastebin.com/fhtisimf

**Comment by michaelzusev** [comment]
Hi @dnrm, can you give a brief explanation on how to do this? I have never worked with Java before. Thanks in advanced.
