### ISSUE TITLE
Can't execute on MacOS Ventura on M1 Pro

### ISSUE THREAD

**Issue by sussyboiiii** [MaxiHuHe04/iTunes-Backup-Explorer#30]
Hello, 
I'm uncertain if this problem is on my side or wherever, but when I'm trying to open the .jar nothing happens when I just click on it (yes I've done all steps and also got Java 20 installed) if I try to execute from the terminal though I get the error 
`(mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64'))` 
after googling it I only found people having this problem in python but this is java, ChatGPT said it's compiled for the wrong architecture, but I thought java is universal and also you can't trust ChatGPT, then I tried running terminal with Rosetta and also the Java Launcher but nothing worked. Looking forward to you suggestions and help.
Thanks!

**Comment by agentdr8** [comment]
I ran into this same issue on my M1 MBP, and was able to at least get the utility to run once I installed Java 21 with included JavaFX from Azul. It didn't seem to be able to do much with my test iPhone backup though, so there may still be some incompatibilities.

**Comment by MaxiHuHe04** [comment]
Hey, can you launch other Java programs in your environment? This looks more of an installation issue of Java. Try Azul Zulu for arm64 with JavaFX like agentdr8 recommended: https://www.azul.com/downloads/?version=java-21-lts&os=macos&architecture=arm-64-bit&package=jdk-fx#zulu

**Comment by sussyboiiii** [comment]
Thanks! This solved my problem, I thought I had java properly installed but apparently not. Thanks man.

**Comment by MaxiHuHe04** [comment]
Glad to hear that!
