### ISSUE TITLE
How to run?

### ISSUE THREAD

**Issue by zidanmahmoud** [MaxiHuHe04/iTunes-Backup-Explorer#4]
Sorry for my lack of knowledge.
For someone who is not familiar with Java, how to actually run the GUI? It is currently not mentioned in [README.md](/MaxiHuHe04/iTunes-Backup-Explorer/blob/master/README.md)

I am running on Ubuntu 20.04

**Comment by globaldeejays** [comment]
I've tried importing into Eclipse IDE and running as Java project but it had hundreds of errors and couldn't run. I'd like to know how to run it as well

**Comment by MaxiHuHe04** [comment]
I finally published a release now. You can download it [here](https://github.com/MaxiHuHe04/iTunes-Backup-Explorer/releases/latest) and start the program using `java -jar itunes-backup-explorer-1.0.jar`. The only requirement is Java 11+. The jar file should also work on Linux, but I haven't tested it yet. If it doesn't work, please let me know. 
If you want to launch it from source in an IDE or the terminal, simply use the Maven command `mvn exec:exec`.
