### ISSUE TITLE
Many voice recordings missing / all lack their original saved titles.

### ISSUE THREAD

**Issue by Yolakalemowa** [MaxiHuHe04/iTunes-Backup-Explorer#47]
Hi.

I was able to find the voice recordings but only a few hundred out of around 900 saved in my phone.

Also, non of them have the titles I saved them in on my phone. 

Do you think there's a way to fix that?

**Comment by MaxiHuHe04** [comment]
Hi @Yolakalemowa,

You should find the recordings of the Voice Memos app in the Files tab in ``Application Groups/AppDomainGroup-group.com.apple.VoiceMemos.shared/Recordings`` as .m4a files.

If there really are recordings missing in the folder inside the backup, I'm afraid I can't do anything either. Maybe something went wrong or they are on iCloud and the phone decides it doesn't have to backup them locally.

In one of my backups, there are manifest.plist files in .composition folders which contain the title for some of the more recent ones of them.
But the titles are also included in the audio files as metadata. You can access them for example by installing ffmpeg and executing the following command:
```ffprobe -loglevel error -show_entries format_tags=title -of default=nk=1:nw=1 "recording_file.m4a"``` (replace recording_file with the name of a file)

If you are not familiar with using the command line, I could help rename the files accordingly or write the titles in a text file or something like that.

**Comment by Yolakalemowa** [comment]
> You should find the recordings of the Voice Memos app in the Files tab in `Application Groups/AppDomainGroup-group.com.apple.VoiceMemos.shared/Recordings` as .m4a files.

Hi thank you for responding. I couldn't find anything in this folder:

![image](https://github.com/MaxiHuHe04/iTunes-Backup-Explorer/assets/41283612/7509f02c-1ca3-4784-a5b8-779b89a4d7ea)

What do you think?

**Comment by MaxiHuHe04** [comment]
Apparently could also be in `MediaDomain/Media/Recordings`.
Do you have the recordings in the Voice Memos app on the phone or in another app?
Could you also post a screenshot of the File Search tab after typing in `%` and `%.m4a` in the search boxes and clicking on Search?

**Comment by Yolakalemowa** [comment]
ok so apparently they're not even in the MediaDomain/Media/Recordings but in MediaDomain/Library/Recordings.

and here's the screenshot you asked for:

![image](https://github.com/MaxiHuHe04/iTunes-Backup-Explorer/assets/41283612/c0b41057-ea21-47d6-a451-7fb9c20e8c29)

**Comment by MaxiHuHe04** [comment]
Interesting... apparently it is different on every device and iOS version :joy:

Now, are there still some missing or do you have everything you searched for?

**Comment by Yolakalemowa** [comment]
your instructions about titles and ffmpeg thing. It can retrieve and restore each vn's title to it? 

and do I just run ffmpeg from any directory?

thank you so much for your patience. also... FUCK APPLE this is absolutely bullshit.

**Comment by MaxiHuHe04** [comment]
The command at this point just tells you the name for one recording you give it. If you replace `recording_file.m4a` with the full path of the extracted file, you can run it from anywhere, but if you are in the same directory, you can just use the name of the file.

**Comment by Yolakalemowa** [comment]
thanks man. 

I apprecaite it. I think we can close this issue? unless there's a way for the program to retrieve the recordings with their saved titles? or not possible?

**Comment by MaxiHuHe04** [comment]
Which operating system do you use? On my Windows system, it automatically shows the title in a column in the folder with the extracted recordings.
![image](https://github.com/MaxiHuHe04/iTunes-Backup-Explorer/assets/12913518/9158ec87-f694-422d-8b9b-3c1a871782a6)

**Comment by Yolakalemowa** [comment]
oh shoot yeah they're there... sorry for troubling you!

**Comment by MaxiHuHe04** [comment]
Alright, no problem! 👍
