### ISSUE TITLE
Notes in backup

### ISSUE THREAD

**Issue by McAshesha** [MaxiHuHe04/iTunes-Backup-Explorer#48]
What path and domain can I find notes and note attachments?

**Comment by MaxiHuHe04** [comment]
You should be able to find the notes and attachments in the domain `AppDomainGroup-group.com.apple.notes`. The notes are stored in the database `NoteStore.sqlite`. If you just need the attachments, you can export the "Media" directory and/or "Accounts/<...>/Media" directory in there. If you want to export the notes in a format you can view, there is a project I just found which you can modify a bit to convert the notes to HTML for example: https://github.com/dunhamsteve/notesutils/tree/master

**Comment by MaxiHuHe04** [comment]
@McAshesha I will close this issue now. If you still have questions, feel free to re-open it.
