### ISSUE TITLE
Unable to access the jar file

### ISSUE THREAD

**Issue by Trombettino** [MaxiHuHe04/iTunes-Backup-Explorer#49]
Hi, i'm using windows to install this program but i can't. It says that it's unable to run the jar file in the cmd or double-clicking the file. Here the picture. Help me please 'cause i really need to backup my photoes and file on my iPhone. Thank you.
![image](https://github.com/MaxiHuHe04/iTunes-Backup-Explorer/assets/124807786/a0713296-2e05-4b65-b50e-6cb3f1ea8693)
![image](https://github.com/MaxiHuHe04/iTunes-Backup-Explorer/assets/124807786/f9d49cb5-2fad-40b3-a434-8a064c00ab2e)

**Comment by MaxiHuHe04** [comment]
Hey @Trombettino,
I think you tried to launch the program from the wrong directory. You can change to the folder you downloaded the file to using `cd <directory>` (e.g. `cd Downloads`) or right click on the file while holding shift, copy the path and paste the whole path in the java -jar command.

**Comment by Trombettino** [comment]
The problem was java but i solved it anyways. thank u
