### ISSUE TITLE
Cannot run app on macOS 15

### ISSUE THREAD

**Issue by Yn-Skr** [MaxiHuHe04/iTunes-Backup-Explorer#50]
OUTPUT: Jun 20, 2024 10:18:36 AM com.sun.javafx.application.PlatformImpl startup
WARNING: Unsupported JavaFX configuration: classes were loaded from 'unnamed module @6d6a0534'
Jun 20, 2024 10:18:41 AM com.sun.glass.ui.mac.MacApplication lambda$waitForReactivation$6
WARNING: Timeout while waiting for app reactivation
*** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: '0x0 is an invalid NSTrackingRectTag. Common possible reasons for this are: 1. already removed this trackingRectTag, 2. Truncated the NSTrackingRectTag to 32bit at some point.'
*** First throw call stack:
(
	0   CoreFoundation                      0x00007ff816a30946 __exceptionPreprocess + 242
	1   libobjc.A.dylib                     0x00007ff8165180f0 objc_exception_throw + 62
	2   Foundation                          0x00007ff817a97599 -[NSAssertionHandler handleFailureInMethod:object:file:lineNumber:description:] + 362
	3   AppKit                              0x00007ff81ab7b51c -[_NSTrackingAreaAKViewHelper removeTrackingRect:] + 199
	4   libglass.dylib                      0x000000010f7ca449 Java_com_sun_glass_ui_mac_MacApplication__1getMacKey + 3593
	5   libglass.dylib                      0x000000010f7cf038 Java_com_sun_glass_ui_mac_MacApplication__1getMacKey + 23032
	6   AppKit                              0x00007ff81a2f0233 -[NSView setFrame:] + 347
	7   libglass.dylib                      0x000000010f7cf095 Java_com_sun_glass_ui_mac_MacApplication__1getMacKey + 23125
	8   AppKit                              0x00007ff81a30032a -[NSView resizeWithOldSuperviewSize:] + 816
	9   AppKit                              0x00007ff81a2ffbc2 -[NSView resizeSubviewsWithOldSize:] + 499
	10  AppKit                              0x00007ff81a2dfea7 -[NSView setFrameSize:] + 1198
	11  AppKit                              0x00007ff81a2f0233 -[NSView setFrame:] + 347
	12  AppKit                              0x00007ff81a30032a -[NSView resizeWithOldSuperviewSize:] + 816
	13  AppKit                              0x00007ff81a2ffbc2 -[NSView resizeSubviewsWithOldSize:] + 499
	14  AppKit                              0x00007ff81a2dfea7 -[NSView setFrameSize:] + 1198
	15  AppKit                              0x00007ff81a2fe63b -[NSThemeFrame setFrameSize:] + 466
	16  AppKit                              0x00007ff81a2fdd3f -[NSWindow _oldPlaceWindow:fromServer:] + 822
	17  AppKit                              0x00007ff81a2fc68c -[NSWindow _setFrameCommon:display:fromServer:] + 1859
	18  libglass.dylib                      0x000000010f7c227f getImage + 6799
	19  libglass.dylib                      0x000000010f7c1cec getImage + 5372
	20  libglass.dylib                      0x000000010f7c1f59 getImage + 5993
	21  libglass.dylib                      0x000000010f7d92ce Java_com_sun_glass_ui_mac_MacWindow__1setBounds2 + 446
	22  ???                                 0x0000000120630b3c 0x0 + 4838329148
	23  ???                                 0x000000012062c411 0x0 + 4838310929
	24  ???                                 0x000000012062c411 0x0 + 4838310929
	25  ???                                 0x000000012062c411 0x0 + 4838310929
	26  ???                                 0x000000012062c917 0x0 + 4838312215
)
libc++abi: terminating due to uncaught exception of type NSException
[1]    7602 abort      java -jar itunes-backup-explorer-1.4.jar

**Comment by MaxiHuHe04** [comment]
Hey @Yn-Skr,
Which Java version do you have installed? Some make problems with JavaFX on macOS / Apple processors. Have you tried Azul Zulu JDK FX? You can get it from here: https://www.azul.com/downloads/?version=java-21-lts&os=macos&architecture=arm-64-bit&package=jdk-fx#zulu

**Comment by Yn-Skr** [comment]
I'm on intel and I think I have oracles jdk 22 but ill give it a try

**Comment by MaxiHuHe04** [comment]
@Yn-Skr could you try [version 1.5](https://github.com/MaxiHuHe04/iTunes-Backup-Explorer/releases/tag/v1.5) if the issue still persists? Combined with Azul Zulu FX, it should work on macOS 15.

**Comment by Yn-Skr** [comment]
Hi, I will defenatly try it later today and will update you.

**Comment by Yn-Skr** [comment]
@MaxiHuHe04 Ok so i tested it and everything seems to work 👍.

**Comment by MaxiHuHe04** [comment]
Happy to hear that!
