### ISSUE TITLE
Unable to access the Jar file.

### ISSUE THREAD

**Issue by DanGames96** [MaxiHuHe04/iTunes-Backup-Explorer#51]
So I tried using the command prompt and it says unable to access this jar file, then I tried double clicking and Java gave me the error of. A Java Exception has occured, I really don't know much about those, think i could get some guidance?

**Comment by MaxiHuHe04** [comment]
Which version of Java do you have installed?
Could you post a screenshot of the terminal after you try to execute the command?
Maybe you tried to launch the program from the wrong directory or with the wrong file name. You can change to the folder you downloaded the jar file to using cd <directory> (e.g. cd Downloads) or right click on the file while holding shift, copy the path and paste the whole path after java -jar in the command line.

**Comment by DanGames96** [comment]
For the Java version, I assume its 4.1.1 well the latest version i think?
![image_2024-06-28_182216357](https://github.com/MaxiHuHe04/iTunes-Backup-Explorer/assets/104238960/cd5378a9-e157-4d82-935a-9b2d6b6a423e)

**Comment by MaxiHuHe04** [comment]
The latest version would be 22 😅. You can get it by typing in java -version.

I assume you didn't download the program to C:\Windows\System32. So you have to navigate to the right directory using cd first, or open the command prompt directly in the right folder by shift-right-clicking in the explorer and then "Open command window here" or something line "Open PowerShell here"

**Comment by DanGames96** [comment]
That was it, i had version 8 XD just downloaded version 22 and it worked, thank you!
