### ISSUE TITLE
Itunes backup is just a folder with more folders - how to open? 

### ISSUE THREAD

**Issue by zrodrps** [MaxiHuHe04/iTunes-Backup-Explorer#61]
Hi, sorry to be a total newb but my itunes backup is just a folder with many folders inside 0-99 etc. How can I open this with the explorer?

**Comment by zrodrps** [comment]
> @zrodrps Which device and iOS version do you have?

Iphone 6s 15.8.2

**Comment by MaxiHuHe04** [comment]
Additionally to all the folders, there should also be about 4 files in the backup directory.
If it is saved in the default location, the program should automatically find and show it. If the sidebar is empty, you can manually open it from the File menu by selecting the Manifest.db file in the backup directory.

**Comment by zrodrps** [comment]
Thanks I got it now. I saw those files eventually and found out I had to double click, not single, on the folders in the explorer to open up in the right pane :) Sry to disturb and thanks for replying and making the app.
