### ISSUE TITLE
Export selected domains only export one domain

### ISSUE THREAD

**Issue by Dobatymo** [MaxiHuHe04/iTunes-Backup-Explorer#9]
Hi, thanks for this great app!
When I select multiple domains and chose "export selected domains" it only exports one of them, but not all. It should put each domain in a subfolder.

Using `itunes-backup-explorer-1.2.jar` and `java 17.0.5 2022-10-18 LTS`.

**Comment by MaxiHuHe04** [comment]
Hey @Dobatymo!
Sorry for taking so long to reply. Sadly, I cannot reproduce this issue. In case it is still relevant for you, could you reopen this and give me some more details?
- Which OS do you use?
- Which domains did you select?
- Please download version 1.3 and run the program using `java -jar itunes-backup-explorer-1.3.jar` in a terminal. Then post the log output after exporting the domains if there is any.
